version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: desafio_spring_inicial_db
    environment:
      POSTGRES_DB: desafio_spring_inicial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - desafio_spring_network

volumes:
  postgres_data:

networks:
  desafio_spring_network: